/**
 * Generate the service worker after a build.
 *
 * Vite hashes its output filenames, so the list of files to precache is only
 * known once the build has run. This walks `dist`, writes the list into a
 * service worker template, and stamps it with a version derived from the file
 * contents — so a deploy that changes nothing produces the same worker and does
 * not needlessly evict a working offline copy.
 */

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, '..', 'dist');

function walk(directory) {
  const found = [];
  for (const entry of readdirSync(directory)) {
    const full = join(directory, entry);
    if (statSync(full).isDirectory()) found.push(...walk(full));
    else found.push(full);
  }
  return found;
}

const files = walk(dist)
  .map((file) => relative(dist, file).split('\\').join('/'))
  // Source maps are large and only useful with devtools open, which needs the
  // network anyway.
  .filter((file) => !file.endsWith('.map') && file !== 'sw.js')
  .sort();

const hash = createHash('sha256');
for (const file of files) {
  hash.update(file);
  hash.update(readFileSync(join(dist, file)));
}
const version = hash.digest('hex').slice(0, 12);

const worker = `/*
 * Swiss Arbiter service worker — generated by scripts/build-sw.mjs.
 *
 * Strategy: precache everything at install, then serve the whole app from the
 * cache first. There is no runtime data to fetch — the tournament lives in
 * IndexedDB — so the network is only ever consulted to pick up a new version.
 */

const VERSION = '${version}';
const CACHE = 'swiss-arbiter-' + VERSION;
const ASSETS = ${JSON.stringify(files.map((f) => './' + f), null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(ASSETS))
      // A new worker should take over as soon as it is ready; the app holds no
      // in-flight server state that a swap could corrupt.
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys.filter((key) => key !== CACHE).map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(request)
        .then((response) => {
          // Cache anything new that belongs to this app, so a page reached for
          // the first time online is available offline afterwards.
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => {
          // Offline and not cached: for a navigation, fall back to the shell so
          // the app still opens.
          if (request.mode === 'navigate') return caches.match('./index.html');
          return Response.error();
        });
    }),
  );
});
`;

writeFileSync(join(dist, 'sw.js'), worker);
console.log(`service worker ${version} precaching ${files.length} files`);
